<h2>Cadeaubon</h2>
<img src="./images/haar.jpg" align="right" width="250" height="321" alt="" />
<p>Verras een ander met een cadeaubon van Haar Knipsels!</p>
<p>Leuk als verjaardagscadeau, iemand te verrassen, om aan iemand te geven als bedankje of zomaar.</p>
<p>De waarde van de cadeaubon kan je zelf bepalen. De bon is na uitgifte 1 jaar geldig en te verzilveren voor al mijn behandelingen. (De cadeaubon is niet inwisselbaar voor geld en niet geldig in combinatie met aanbiedingen / kortingen)</p>
