<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xml:lang="nl" lang="nl" xmlns="http://www.w3.org/1999/xhtml">
  <head>
    <title>Haar Knipsels - Thuiskapster in omgeving Soest en Amersfoort</title>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta name="keywords" content="kapster, thuiskapster, Maeike van den Heuvel, Maeike, Soest, Amersfoort, Goldwell, knippen, kinderen, heren, dames, bruidskapsel, feestkapsel, opsteken, permanent, deelpermanent, ondersteuning, verven, verf, kleurspoeling, highlights" />
    <meta name="description" content=""Even" naar de kapper is niet altijd even. Je moet er de deur voor uit en ondanks dat u een afspraak heeft, is het toch vaak langer wachten voor u wordt geholpen. Dit is niet meer nodig als u een afspraak bij mij heeft gemaakt." />
    <meta http-equiv="content-language" content="nl" />
    <meta name="robots" content="all" />
    <meta name="generator" content="Hoest Internet Productions" />
    <meta name="robots" content="all" />
    <link rel="stylesheet" type="text/css" href="./css/default.css">
  </head>
  <body>
    <div id="page">
      <div id="menu">
        <a href="./?p=home"><img src="./images/btn_home.gif" width="98" height="39" alt="Home" /></a>
        <!--a href="./?p=hairextensions"><img src="./images/btn_hairextensions.gif" width="207" height="34" alt="Hairextensions" /></a-->
        <a href="./?p=producten"><img src="./images/btn_producten.gif" width="151" height="35" alt="Producten" /></a>
        <a href="./?p=prijzen"><img src="./images/btn_prijzen.gif" width="112" height="41" alt="Prijzen" /></a>
        <a href="./?p=cadeaubon"><img src="./images/btn_cadeaubon.gif" width="156" height="33" alt="Cadeaubon" /></a>
        <a href="./?p=contact"><img src="./images/btn_contact.gif" width="122" height="37" alt="Contact" /></a>
      </div>
      <div id="content">
        <div id="header">
          <a href="/"><img src="./images/logo.gif" width="541" height="98" alt="Haar Knipsels" /></a>
        </div>
        <div id="text">
