<div class="center btm10">
  <img src="./images/home.jpg" width="500" height="74" alt="" />
</div>
<p>"Even" naar de kapper is niet altijd even. Je moet er de deur voor uit en ondanks dat u een afspraak heeft, is het toch vaak langer wachten voor u wordt geholpen.</p>
<p>Dit is niet meer nodig als u een afspraak bij mij heeft gemaakt.</p>
<p>Ik kom graag bij u thuis om te knippen, verven of voor een bruidskapsel, eigenlijk wat u maar wilt. Na het behalen van mijn kappersdiploma 12 jaar geleden heb ik veel ervaring opgedaan in diverse kapsalons. Momenteel werk ik met professionele producten van Goldwell.</p>
<p>Met kinderen kan ik ook goed overweg, voor hen neem ik altijd een klein presentje mee.<br />
Ze vinden het vaak prettiger als ze in hun eigen omgeving worden geknipt.</p>
<p>DUS… als u in Soest woont, bel dan gerust voor een afspraak.</p>
<p><strong>Maeike</strong></p>
