<h2>Prijzen</h2>
<h3>Groepskorting!</h3>
<p>Bij 5 personen of meer op 1 adres 10% korting per persoon.</p>
<table>
  <tr>
    <th>Knippen</th>
    <th>Bedrag in Euro's</th>
  </tr>
  <tr>
    <td>Kinderen 0 t/m 6 jr.</td>
    <td class="price">&#8364; 10,00</td>
  </tr>
  <tr>
    <td>Kinderen 7 t/m 12 jr.</td>
    <td class="price">&#8364; 12,50</td>
  </tr>
  <tr>
    <td>Dames knippen</td>
    <td class="price">&#8364; 17,50</td>
  </tr>
  <tr>
    <td>Dames knippen/drogen</td>
    <td class="price">&#8364; 19,50</td>
  </tr>
  <tr>
    <td>Dames knippen/modelfohnen</td>
    <td class="price">&#8364; 23,00</td>
  </tr>
  <tr>
    <td>Dames modelfohnen</td>
    <td class="price">&#8364; 17,00</td>
  </tr>
  <tr>
    <td>Heren knippen</td>
    <td class="price">&#8364; 16,00</td>
  </tr>
</table>
<table>
  <tr>
    <th>Kleuren</th>
    <th>Bedrag in Euro's</th>
  </tr>
  <tr>
    <td>Verf vanaf</td>
    <td class="price">&#8364; 23,00</td>
  </tr>
  <tr>
    <td>Spoeling vanaf</td>
    <td class="price">&#8364; 18,00</td>
  </tr>
  <tr>
    <td>High/lowlights per folie</td>
    <td class="price">&#8364; 2,50</td>
  </tr>
</table>
<table>
  <tr>
    <th>Permanent</th>
    <th>Bedrag in Euro's</th>
  </tr>
  <tr>
    <td>Deelpermanent</td>
    <td class="price">&#8364; 38,50</td>
  </tr>
  <tr>
    <td>Permanent</td>
    <td class="price">&#8364; 53,00</td>
  </tr>
  <tr>
    <td>Ondersteuning</td>
    <td class="price">&#8364; 38,50</td>
  </tr>
</table>
<table>
  <tr>
    <th>Feest- en bruidskapsels</th>
    <th>Bedrag in Euro's</th>
  </tr>
  <tr>
    <td>Bruidskapsel incl. proefkapsel</td>
    <td class="price">&#8364; 86,00</td>
  </tr>
  <tr>
    <td>Opsteken</td>
    <td class="price">&#8364; 18,00</td>
  </tr>
  <tr>
    <td>Opsteken met carmenset</td>
    <td class="price">&#8364; 28,00</td>
  </tr>
</table>
