<h2>Producten</h2>
<p>Ik gebruik professionele haarproducten van shampoos van Dualsenses en stylingproducten van StyleSign.</p>
<div class="center btm10">
  <img src="./images/dualsenses.jpg" width="320" height="125" alt="Dualsenses" />
</div>

<table>
  <tr>
    <th>DUALSENSES</th>
    <th>Bedrag in Euro's</th>
  </tr>
  <tr>
    <td colspan="2">Ultra Volume</td>
  </tr>
  <tr>
    <td>Gel-Shampoo</td>
    <td class="price">&#8364; 10,80
  </tr>
  <tr>
    <td>Gel – Conditioner</td>
    <td class="price">&#8364; 13,85</td>
  </tr>
  <tr>
    <td>Leave-in Boost Spray</td>
    <td class="price">&#8364; 13,35</td>
  </tr>
  <tr>
    <td colspan="2">&#160;</td>
  </tr>
  <tr>
    <td colspan="2">Rich Repair</td>
  </tr>
  <tr>
    <td>Shampoo</td>
    <td class="price">&#8364; 10,80</td>
  </tr>
  <tr>
    <td>Conditioner</td>
    <td class="price">&#8364; 13,85</td>
  </tr>
  <tr>
    <td>Leave-in Cream Fluid</td>
    <td class="price">&#8364; 13,35</td>
  </tr>
  <tr>
    <td colspan="2">&#160;</td>
  </tr>
  <tr>
    <td colspan="2">Color</td>
  </tr>
  <tr>
    <td>Shampoo</td>
    <td class="price">&#8364; 10,80</td>
  </tr>
  <tr>
    <td>Conditioner</td>
    <td class="price">&#8364; 13,85</td>
  </tr>
  <tr>
    <td>Leave-in Mousse</td>
    <td class="price">&#8364; 13,35</td>
  </tr>
  <tr>
    <td>Leave-in Cream Fluid</td>
    <td class="price">&#8364; 13,35</td>
  </tr>
  <tr>
    <td colspan="2">&#160;</td>
  </tr>
  <tr>
    <td colspan="2">Curly Twist</td>
  </tr>
  <tr>
    <td>Shampoo</td>
    <td class="price">&#8364; 10,80</td>
  </tr>
  <tr>
    <td>Conditioner</td>
    <td class="price">&#8364; 13,85</td>
  </tr>
  <tr>
    <td>Leave-in 2 phase Spray</td>
    <td class="price">&#8364; 13,35</td>
  </tr>
  <tr>
    <td colspan="2">&#160;</td>
  </tr>
  <tr>
    <td colspan="2">Scalp Regulation</td>
  </tr>
  <tr>
    <td>Anti Dandruff Shampoo</td>
    <td class="price">&#8364; 10,80</td>
  </tr>
  <tr>
    <td>Sensitive Shampoo</td>
    <td class="price">&#8364; 10,80</td>
  </tr>
  <tr>
    <td>Deep Cleansing Shampoo</td>
    <td class="price">&#8364; 10,80</td>
  </tr>
</table>

<div class="center">
  <img src="./images/stylesign.jpg" width="320" height="78" alt="StyleSign" />
</div>

<table>
  <tr>
    <th>StyleSign</th>
    <th>Bedrag in Euro's</th>
  </tr>
  <tr>
    <td colspan="2">Natural </td>
  </tr>
  <tr>
    <td>Just Smooth (milk)</td>
    <td class="price">&#8364; 13,40</td>
  </tr>
  <tr>
    <td>Structure me (spray)</td>
    <td class="price">&#8364; 13,40</td>
  </tr>
  <tr>
    <td colspan="2">&#160;</td>
  </tr>
  <tr>
    <td colspan="2">Gloss </td>
  </tr>
  <tr>
    <td>Glamour Whip (mousse)</td>
    <td class="price">&#8364; 15,05</td>
  </tr>
  <tr>
    <td>Magic Finish (spray)</td>
    <td class="price">&#8364; 13,40</td>
  </tr>
  <tr>
    <td>Spun Shine (shine cream)</td>
    <td class="price">&#8364; 13,40</td>
  </tr>
  <tr>
    <td>Melting Diamonds (brilliance drops)</td>
    <td class="price">&#8364; 15,60</td>
  </tr>
  <tr>
    <td>Diamond Gloss (shine spray)</td>
    <td class="price">&#8364; 13,40</td>
  </tr>
  <tr>
    <td colspan="2">&#160;</td>
  </tr>
  <tr>
    <td colspan="2">Volume</td>
  </tr>
  <tr>
    <td>Double Boost (spray)</td>
    <td class="price">&#8364; 15,00</td>
  </tr>
  <tr>
    <td>Power Whip (mousse)</td>
    <td class="price">&#8364; 15,05</td>
  </tr>
  <tr>
    <td>Top Whip (mousse)</td>
    <td class="price">&#8364; 15,05</td>
  </tr>
  <tr>
    <td>Big Finish (spray)</td>
    <td class="price">&#8364; 13,40</td>
  </tr>
  <tr>
    <td>Lagoom Jam (gel)</td>
    <td class="price">&#8364; 13,40</td>
  </tr>
  <tr>
    <td>Jelly Boost (spray)</td>
    <td class="price">&#8364; 13,40</td>
  </tr>
  <tr>
    <td colspan="2">&#160;</td>
  </tr>
  <tr>
    <td colspan="2">Straight</td>
  </tr>
  <tr>
    <td>Hot Form (lotion)</td>
    <td class="price">&#8364; 13,40</td>
  </tr>
  <tr>
    <td>Flat Marvel (balm)</td>
    <td class="price">&#8364; 15,00</td>
  </tr>
  <tr>
    <td>Sleek Perfection (serum)</td>
    <td class="price">&#8364; 15,00</td>
  </tr>
  <tr>
    <td colspan="2">&#160;</td>
  </tr>
  <tr>
    <td colspan="2">Curl </td>
  </tr>
  <tr>
    <td>Curl Love (cream)</td>
    <td class="price">&#8364; 13,40</td>
  </tr>
  <tr>
    <td>Crystal Turn (gel-wax)</td>
    <td class="price">&#8364; 15,00</td>
  </tr>
  <tr>
    <td>Twist Around (lotion)</td>
    <td class="price">&#8364; 13,40</td>
  </tr>
  <tr>
    <td colspan="2">&#160;</td>
  </tr>
  <tr>
    <td colspan="2">Texture</td>
  </tr>
  <tr>
    <td>Mellogoo (modelling paste)</td>
    <td class="price">&#8364; 15,00</td>
  </tr>
  <tr>
    <td>Superego (cream)</td>
    <td class="price">&#8364; 13,40</td>
  </tr>
  <tr>
    <td>Hardliner (gel)</td>
    <td class="price">&#8364; 13,40</td>
  </tr>
  <tr>
    <td>Sprayer (spray)</td>
    <td class="price">&#8364; 13,40</td>
  </tr>
  <tr>
    <td>Composer (wet look gel)</td>
    <td class="price">&#8364; 13,40</td>
  </tr>
  <tr>
    <td>Unlimitor (spray wax)</td>
    <td class="price">&#8364; 13,40</td>
  </tr>
  <tr>
    <td>Pump Freezer (spray)</td>
    <td class="price">&#8364; 15,00</td>
  </tr>
  <tr>
    <td>Roughman (cream paste)</td>
    <td class="price">&#8364; 15,00</td>
  </tr>
</table>
